# Generated by Django 3.1.1 on 2020-10-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='listing',
        ),
        migrations.AddField(
            model_name='listing',
            name='whatchListings',
            field=models.ManyToManyField(to='auctions.WatchList'),
        ),
    ]
