# Generated by Django 3.1.1 on 2020-10-03 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201003_0714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='current_price',
            new_name='start_bid',
        ),
    ]
