# Generated by Django 3.1.1 on 2020-10-03 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20201003_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='user',
        ),
    ]
