# Generated by Django 3.1.1 on 2020-10-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_listing_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='whatchListings',
        ),
        migrations.AddField(
            model_name='listing',
            name='watchListings',
            field=models.ManyToManyField(related_name='listings', to='auctions.WatchList'),
        ),
    ]
